version: '2.1'

services:
  louisehuyton-spring2:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/louisehuyton-spring2
    ports:
      - $SERVER_PORT:$SERVER_PORT
